[project]
name = "Splat-LOAM"
version = "0.1.0"
authors = ["Emanuele Giacomini <giacomini@diag.uniroma1.it>"]
channels = ["nvidia/label/cuda-11.8.0", "conda-forge"]
platforms = ["linux-64"]

[tasks]

[system-requirements]
libc = "2.31" # Minimum required version for Open3d

[dependencies]
python = ">=3.11,<3.13"


[pypi-dependencies]
omegaconf = ">=2.3.0, <3"
torch = {version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu118"}
torchvision = {version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu118"}
pytransform3d = ">=3.14.0, <4"
open3d = "==0.19"
rosbags = ">=0.10.9, <0.11"
natsort = ">=8.4.0, <9"
typer = ">=0.15.3, <0.16"
pyprojections = ">=0.0.3, <0.0.4"

