inherit_from: configs/oxspires/oxspires.yaml
data:
  dataset_type: oxspires
  cloud_reader:
    cloud_folder: /workspace/data/oxford-spires/keble-college-02/
  trajectory_reader:
    filename: /workspace/data/oxford-spires/keble-college-02/gt-tum.txt
  skip_clouds_wno_sync: True
mapping:
  num_iterations: 500
  densify_threshold_egeom: -1
  densify_threshold_opacity: 0.2
  densify_percentage: 0.40
  prob_view_last_keyframe: null
  pruning_min_opacity: 0.1
  pruning_min_size: 0.0
  pruning_max_size: 1.0
  opt_lambda_alpha: 0.3
  opt_lambda_normal: 0.8
  opt_scaling_max: 0.1
  opt_scaling_max_penalty: 1.0
  lmodel_threshold_ngaussians: null
  lmodel_threshold_nkeyframes: 30
tracking:
  method: gt
  keyframe_threshold_distance: -1
  keyframe_threshold_fitness: -1
  keyframe_threshold_nframes: 5
